version: '3'

services:

  server:
    build: 
      context: .
      dockerfile: ./Dockerfiles/docker/server/Dockerfile
    ports:
      - "3001:3001"

  client1:
    build:
      context: .
      dockerfile: ./Dockerfiles/docker/client/Dockerfile
    depends_on:
      - server

  client2: 
    build:
      context: .
      dockerfile: ./Dockerfiles/docker/client/Dockerfile
    depends_on:
      - server
    

  client3:
    build:
      context: .
      dockerfile: ./Dockerfiles/docker/client/Dockerfile
    depends_on:
      - server
  
  client4:
    build:
      context: .
      dockerfile: ./Dockerfiles/docker/client/Dockerfile
    depends_on:
      - server